"""Add is_avi=ailable

Revision ID: 02318fffa88f
Revises: 
Create Date: 2025-05-08 13:02:02.202326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02318fffa88f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_status', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('order_status')

    # ### end Alembic commands ###
