"""Add HSN field to Product table

Revision ID: 8411cebf7a25
Revises: 
Create Date: 2025-04-14 11:38:08.433040

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8411cebf7a25'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wishlist_items', schema=None) as batch_op:
        batch_op.drop_column('spec_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wishlist_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('spec_id', mysql.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
